---
- name: Configurar servidor web
  hosts: localhost
  become: yes

  tasks:
    - name: Instalar nginx
      package:
        name: nginx
        state: present

    - name: Iniciar y habilitar nginx
      service:
        name: nginx
        state: started
        enabled: yes
